export const menuItem = [
    {
        id:'/app/home',
        title:'首页',
        icon:'desktop',
        child:[]
    },
    {
        id:'/app/order/',
        title:'order',
        icon:'team',
        child:[
            {
                id:'/app/order/list1',
                title:'测试2-1'
            },
            {
                id:'/app/order/list2',
                title:'测试2-2'
            }
        ]
    },
    {
        id:'/app/home/list',
        title:'list',
        icon:'user',
        src:'/app/home/list',
        child:[]
    },
    {
        id:'/app/home/config',
        title:'config',
        icon:'team',
        child:[]
    }
];