export const menuItem = [
    {
        id:'/app/home',
        title:'面板',
        icon:'desktop',
        child:[]
    },
    {
        id:'/app/test/',
        title:'测试',
        icon:'team',
        child:[
            {
                id:'/app/test/test1',
                title:'测试1'
            },
            {
                id:'/app/test/test2',
                title:'测试2'
            }
        ]
    },
    {
        id:'/app/list',
        title:'list',
        icon:'user',
        src:'/app/list',
        child:[]
    },
    {
        id:'/app/config',
        title:'config',
        icon:'team',
        child:[]
    }
];